[package]
name = "git-pr-blame"
version = "0.1.0"
authors = ["Joel Nises <joel.nises@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.37"
git2 = "0.13.15"
structopt = "0.3.21"
log = "0.4.11"
env_logger = "0.8.2"