[package]
name = "git-suggest-reviewers"
version = "1.2.1"
authors = ["Joel Nises <joel.nises@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
structopt = "0.3"
log = "0.4"
stderrlog = "0.5"
indicatif = "0.15"

[dependencies.git2]
# use our own fork to get blame min max line, and no ssh in libz-ng
git = "https://github.com/jnises/git2-rs.git"
rev = "383de230bbe221b4d54859a726b0a23da046e2f5"
default-features = false
features = ["zlib-ng-compat"]
