[package]
name = "git-review-proposal"
version = "0.1.0"
authors = ["Joel Nises <joel.nises@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
git2 = "0.13"
structopt = "0.3"
log = "0.4"
stderrlog = "0.5"
indicatif = "0.15"