name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  win_build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: git-suggest-reviewers_win_x64
        path: target/release/git-suggest-reviewers.exe

  mac_build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: |
        cargo build --release
        cd target/release
        tar cz git-suggest-reviewers > ../../git-suggest-reviewers_mac_x64.tgz
    - uses: actions/upload-artifact@v2
      with:
        name: git-suggest-reviewers_mac_x64
        path: target/release/git-suggest-reviewers

  release:
    needs: [win_build, mac_build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: git-suggest-reviewers_mac_x64
        path: mac_x64/git-suggest-reviewers
    - uses: actions/download-artifact@v2
      with:
        name: git-suggest-reviewers_win_x64
        path: win_x64/git-suggest-reviewers
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./git-suggest-reviewers_mac_x64
        asset_name: mac_x64/git-suggest-reviewers
        asset_content_type: application/octet-stream
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./git-suggest-reviewers_win_x64
        assert_name: win_x64/git-suggest-reviewers.exe
        asset_content_type: application/octet-stream
